# Offense count: 3
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/default/serverspec/localhost/cron_spec.rb'

# Offense count: 3
Style/GuardClause:
  Exclude:
    - 'resources/d.rb'

# Offense count: 3
Style/RegexpLiteral:
  Exclude:
    - 'test/integration/default/serverspec/localhost/cron_spec.rb'
